"""mining extraction class

Revision ID: 0c53b260bb2a
Revises: 3ee841e66003
Create Date: 2026-09-09 23:04:25.700603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# geoalchemy2 emits Geometry columns into migrations but does not add its
# own import, so autogenerated files fail with NameError without this.
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '0c53b260bb2a'
down_revision: Union[str, Sequence[str], None] = '3ee841e66003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default: NOT NULL on a populated table fails without it.
    op.add_column('fire_predictions', sa.Column('mining_probability', sa.Float(),
                                                nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fire_predictions', 'mining_probability')
    # ### end Alembic commands ###
