"""risk score and incident lifecycle

Revision ID: 3ee841e66003
Revises: 94183362ac9b
Create Date: 2026-09-09 22:46:59.231652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# geoalchemy2 emits Geometry columns into migrations but does not add its
# own import, so autogenerated files fail with NameError without this.
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ee841e66003'
down_revision: Union[str, Sequence[str], None] = '94183362ac9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fire_events', sa.Column('risk_score', sa.Float(), nullable=True))
    op.add_column('fire_events', sa.Column('risk_level', sa.String(), nullable=True))
    op.add_column('fire_events', sa.Column('risk_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('fire_events', sa.Column('risk_components', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # server_default: NOT NULL on a table that already has rows fails without it.
    op.add_column('fire_events', sa.Column('is_actionable', sa.Boolean(), nullable=False,
                                           server_default=sa.false()))
    op.add_column('fire_events', sa.Column('monitoring_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('fire_events', sa.Column('risk_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fire_events', 'risk_history')
    op.drop_column('fire_events', 'monitoring_until')
    op.drop_column('fire_events', 'is_actionable')
    op.drop_column('fire_events', 'risk_components')
    op.drop_column('fire_events', 'risk_updated_at')
    op.drop_column('fire_events', 'risk_level')
    op.drop_column('fire_events', 'risk_score')
    # ### end Alembic commands ###
