"""fire event origin anchor

Revision ID: 68d274865626
Revises: e2cf9e6de347
Create Date: 2026-09-08 15:53:51.473041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# geoalchemy2 emits Geometry columns into migrations but does not add its
# own import, so autogenerated files fail with NameError without this.
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '68d274865626'
down_revision: Union[str, Sequence[str], None] = 'e2cf9e6de347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fire_events', sa.Column('origin_latitude', sa.Float(), nullable=True))
    op.add_column('fire_events', sa.Column('origin_longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fire_events', 'origin_longitude')
    op.drop_column('fire_events', 'origin_latitude')
    # ### end Alembic commands ###
