"""fire intelligence core schema

Revision ID: 77bb9696a010
Revises: 
Create Date: 2026-09-08 13:38:29.108191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77bb9696a010'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('baseline_frp', sa.Float(), nullable=False),
    sa.Column('current_frp', sa.Float(), nullable=False),
    sa.Column('last_detected', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_events_past_90_days', sa.Integer(), nullable=False),
    sa.Column('risk_buffer_radius_km', sa.Float(), nullable=False),
    sa.Column('emergency_contact', sa.String(), nullable=True),
    sa.Column('osm_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingest_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('day_range', sa.Integer(), nullable=False),
    sa.Column('detections_fetched', sa.Integer(), nullable=False),
    sa.Column('detections_inserted', sa.Integer(), nullable=False),
    sa.Column('events_created', sa.Integer(), nullable=False),
    sa.Column('events_updated', sa.Integer(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('osm_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cache_key', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('radius_m', sa.Integer(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('element_count', sa.Integer(), nullable=False),
    sa.Column('geometry_quality', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key')
    )
    op.create_table('fire_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('first_detected', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_detected', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('detection_count', sa.Integer(), nullable=False),
    sa.Column('frp_max_mw', sa.Float(), nullable=False),
    sa.Column('frp_mean_mw', sa.Float(), nullable=False),
    sa.Column('frp_latest_mw', sa.Float(), nullable=False),
    sa.Column('brightness_k', sa.Float(), nullable=True),
    sa.Column('detection_confidence_pct', sa.SmallInteger(), nullable=True),
    sa.Column('day_night', sa.String(length=1), nullable=True),
    sa.Column('parent_event_id', sa.String(), nullable=True),
    sa.Column('analysis_status', sa.String(), nullable=False),
    sa.Column('surroundings_status', sa.String(), nullable=True),
    sa.Column('location_name', sa.String(), nullable=True),
    sa.Column('land_cover', sa.String(), nullable=True),
    sa.Column('nearest_facility_id', sa.String(), nullable=True),
    sa.Column('nearest_facility_distance_m', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['nearest_facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['parent_event_id'], ['fire_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fire_events_analysis_status', 'fire_events', ['analysis_status'], unique=False)
    op.create_index('ix_fire_events_last_detected', 'fire_events', ['last_detected'], unique=False)
    op.create_index('ix_fire_events_status_last_detected', 'fire_events', ['status', 'last_detected'], unique=False)
    op.create_table('fire_detections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fire_event_id', sa.String(), nullable=True),
    sa.Column('detection_key', sa.String(length=64), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('acquisition_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('satellite', sa.String(), nullable=False),
    sa.Column('instrument', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('confidence_raw', sa.String(), nullable=True),
    sa.Column('confidence_pct', sa.SmallInteger(), nullable=True),
    sa.Column('brightness_k', sa.Float(), nullable=True),
    sa.Column('bright_ti4', sa.Float(), nullable=True),
    sa.Column('bright_ti5', sa.Float(), nullable=True),
    sa.Column('bright_t31', sa.Float(), nullable=True),
    sa.Column('frp_mw', sa.Float(), nullable=False),
    sa.Column('scan', sa.Float(), nullable=True),
    sa.Column('track', sa.Float(), nullable=True),
    sa.Column('day_night', sa.String(length=1), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fire_event_id'], ['fire_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('detection_key', name='uq_fire_detections_identity')
    )
    op.create_index('ix_fire_detections_acquisition_time', 'fire_detections', ['acquisition_time'], unique=False)
    op.create_index(op.f('ix_fire_detections_fire_event_id'), 'fire_detections', ['fire_event_id'], unique=False)
    op.create_table('weather_anomalies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fire_event_id', sa.String(), nullable=False),
    sa.Column('current_temperature_c', sa.Float(), nullable=True),
    sa.Column('baseline_temperature_c', sa.Float(), nullable=True),
    sa.Column('temperature_anomaly_c', sa.Float(), nullable=True),
    sa.Column('temperature_anomaly_z', sa.Float(), nullable=True),
    sa.Column('temperature_stdev_c', sa.Float(), nullable=True),
    sa.Column('temperature_trend_c_per_day', sa.Float(), nullable=True),
    sa.Column('current_humidity_pct', sa.Float(), nullable=True),
    sa.Column('baseline_humidity_pct', sa.Float(), nullable=True),
    sa.Column('humidity_anomaly_pct', sa.Float(), nullable=True),
    sa.Column('wind_change_ms', sa.Float(), nullable=True),
    sa.Column('precipitation_24h_mm', sa.Float(), nullable=True),
    sa.Column('precipitation_72h_mm', sa.Float(), nullable=True),
    sa.Column('dry_hours', sa.Integer(), nullable=True),
    sa.Column('vpd_kpa', sa.Float(), nullable=True),
    sa.Column('vpd_anomaly_kpa', sa.Float(), nullable=True),
    sa.Column('baseline_samples', sa.SmallInteger(), nullable=False),
    sa.Column('baseline_quality', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fire_event_id'], ['fire_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_anomalies_fire_event_id'), 'weather_anomalies', ['fire_event_id'], unique=False)
    op.create_table('weather_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fire_event_id', sa.String(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('local_hour', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('wind_speed_ms', sa.Float(), nullable=True),
    sa.Column('wind_direction_deg', sa.Float(), nullable=True),
    sa.Column('precipitation_mm', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fire_event_id'], ['fire_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_observations_fire_event_id'), 'weather_observations', ['fire_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_observations_fire_event_id'), table_name='weather_observations')
    op.drop_table('weather_observations')
    op.drop_index(op.f('ix_weather_anomalies_fire_event_id'), table_name='weather_anomalies')
    op.drop_table('weather_anomalies')
    op.drop_index(op.f('ix_fire_detections_fire_event_id'), table_name='fire_detections')
    op.drop_index('ix_fire_detections_acquisition_time', table_name='fire_detections')
    op.drop_table('fire_detections')
    op.drop_index('ix_fire_events_status_last_detected', table_name='fire_events')
    op.drop_index('ix_fire_events_last_detected', table_name='fire_events')
    op.drop_index('ix_fire_events_analysis_status', table_name='fire_events')
    op.drop_table('fire_events')
    op.drop_table('osm_cache')
    op.drop_table('ingest_runs')
    op.drop_table('facilities')
    # ### end Alembic commands ###
