"""osm derived industrial sites replace facility registry

The curated registry could only describe the region it was seeded for: it held
six Gujarat plants while the pipeline polled Telangana, so every fire reported
a "nearest facility" 700 km away. Nearest industrial site now comes from the
same 1 km OpenStreetMap enrichment the classifier already runs, which follows
the AOI wherever it points.

Revision ID: 94183362ac9b
Revises: bfa49e9fac34
Create Date: 2026-09-08 23:12:43.448053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# geoalchemy2 emits Geometry columns into migrations but does not add its
# own import, so autogenerated files fail with NameError without this.
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94183362ac9b'
down_revision: Union[str, Sequence[str], None] = 'bfa49e9fac34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fire_events', sa.Column('nearest_industrial_site', sa.String(), nullable=True))
    op.add_column('fire_events', sa.Column('nearest_industrial_type', sa.String(), nullable=True))
    op.add_column('fire_events', sa.Column('nearest_industrial_distance_m', sa.Float(), nullable=True))
    # server_default: the column is NOT NULL and fire_events already has rows,
    # so without it the ALTER fails on any populated database.
    op.add_column(
        'fire_events',
        sa.Column('inside_industrial_site', sa.Boolean(), nullable=False,
                  server_default=sa.false()),
    )

    # The FK and its column must go before the table they reference, or
    # Postgres refuses the drop for the dependency.
    op.drop_constraint(op.f('fire_events_nearest_facility_id_fkey'), 'fire_events', type_='foreignkey')
    op.drop_column('fire_events', 'nearest_facility_id')
    op.drop_column('fire_events', 'nearest_facility_distance_m')
    op.drop_table('facilities')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fire_events', sa.Column('nearest_facility_distance_m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('fire_events', sa.Column('nearest_facility_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fire_events_nearest_facility_id_fkey'), 'fire_events', 'facilities', ['nearest_facility_id'], ['id'])
    op.drop_column('fire_events', 'inside_industrial_site')
    op.drop_column('fire_events', 'nearest_industrial_distance_m')
    op.drop_column('fire_events', 'nearest_industrial_type')
    op.drop_column('fire_events', 'nearest_industrial_site')
    op.create_table('facilities',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('baseline_frp', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('current_frp', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('last_detected', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('total_events_past_90_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('risk_buffer_radius_km', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('emergency_contact', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('osm_tags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('facilities_pkey'))
    )
    # ### end Alembic commands ###
