"""detection validity assessment

Revision ID: bfa49e9fac34
Revises: b4ad3e0f0523
Create Date: 2026-09-08 19:01:17.560726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# geoalchemy2 emits Geometry columns into migrations but does not add its
# own import, so autogenerated files fail with NameError without this.
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfa49e9fac34'
down_revision: Union[str, Sequence[str], None] = 'b4ad3e0f0523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fire_predictions', sa.Column('validity_verdict', sa.String(), nullable=True))
    op.add_column('fire_predictions', sa.Column('validity_p_real', sa.Float(), nullable=True))
    op.add_column('fire_predictions', sa.Column('validity_model_version', sa.String(), nullable=True))
    op.add_column('fire_predictions', sa.Column('validity_concerns', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('fire_predictions', sa.Column('validity_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fire_predictions', 'validity_steps')
    op.drop_column('fire_predictions', 'validity_concerns')
    op.drop_column('fire_predictions', 'validity_model_version')
    op.drop_column('fire_predictions', 'validity_p_real')
    op.drop_column('fire_predictions', 'validity_verdict')
    # ### end Alembic commands ###
