"""fire event id sequence

Revision ID: e2cf9e6de347
Revises: 77bb9696a010
Create Date: 2026-09-08 13:40:07.588046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# geoalchemy2 emits Geometry columns into migrations but does not add its
# own import, so autogenerated files fail with NameError without this.
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'e2cf9e6de347'
down_revision: Union[str, Sequence[str], None] = '77bb9696a010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SEQUENCE IF NOT EXISTS fire_event_id_seq START 1")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP SEQUENCE IF EXISTS fire_event_id_seq")
